### ISSUE TITLE
Can not work with Create 6.0.3

### ISSUE THREAD

**Issue by yahvk-cuna** [Manwe03/woodencog#5]
Minecraft Version: 1.20.1
Create: 6.0.3
woodencog: 1.1.0-1.20.1

[modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: woodencog, class net.chauvedev.woodencog.WoodenCog
java.lang.NoClassDefFoundError: com/simibubi/create/foundation/ponder/PonderRegistrationHelper
	at net.chauvedev.woodencog.WoodenCog.<clinit>(WoodenCog.java:34) ~[woodencog-1.1.0-1.20.1.jar%23469!/:1.1.0-1.20.1]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.20.1-47.4.0.jar%23472!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:126) ~[fmlcore-1.20.1-47.4.0.jar%23471!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.foundation.ponder.PonderRegistrationHelper
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 15 more

**Comment by Manwe03** [comment]
Currently the mod does not support Create 6.0 and above.
I was working on this but it's a TFC problem. Create uses a JEI version that TFC does not support and heat in the gui does not show up. I can upload a compatible version but the gui problem persits. Besides that it works as normal.

**Comment by yahvk-cuna** [comment]
I'm not sure what impact the GUI issue you mentioned will have; which part of the heat will not be displayed? Anyway, it would be great if there is a version that supports Create 6.0. I would really appreciate it if you could upload it.

**Comment by Manwe03** [comment]
@yahvk-cuna  you might be interested in the new [update](https://www.curseforge.com/minecraft/mc-mods/woodencog/files/6328926)
